apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-seed-js
  namespace: commercefabric-namespace
data:
  orders_mongoDB_init.js: |
    // seed some initial data into the Orders collection in MongoDB

    var orders = [
    ];

    // Switch to your database
    var db = db.getSiblingDB("OrdersDb");

    orders.forEach(function (order) {
        db.orders.updateOne(
            { _id: order._id },
            { $set: order },
            { upsert: true }
        );
    });