apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: commercefabric-namespace
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: commercefabricregistry.azurecr.io/postgres:18.0
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: commercefabricUsers
        ports:
        - containerPort: 5432
