apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-microservice-deployment
  namespace: commercefabric-namespace
  labels:
    app: products-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-microservice
  template:
    metadata:
      labels:
        app: products-microservice
    spec:
      containers:
      - name: products-microservice
        image: commercefabricregistry.azurecr.io/products-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: COMMERCEFABRIC_PRODUCTSERVICE_DB_HOST
          value: mysql
        - name: COMMERCEFABRIC_PRODUCTSERVICE_DB_PORT
          value: "3306"
        - name: COMMERCEFABRIC_PRODUCTSERVICE_DB_NAME
          value: productDB
        - name: COMMERCEFABRIC_PRODUCTSERVICE_DB_USER
          value: root
        - name: COMMERCEFABRIC_PRODUCTSERVICE_DB_PASSWORD
          value: admin
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_PRODUCTS_EXCHANGE
          value: products.exchange
