apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice-deployment
  namespace: commercefabric-namespace
  labels:
    app: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
      - name: users-microservice
        image: commercefabricregistry.azurecr.io/users-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: COMMERCEFABRIC_USERSERVICE_DB_HOST
          value: postgres
        - name: COMMERCEFABRIC_USERSERVICE_DB_NAME
          value: commercefabricUsers
        - name: COMMERCEFABRIC_USERSERVICE_DB_PORT
          value: "5432"
        - name: COMMERCEFABRIC_USERSERVICE_DB_USER
          value: postgres
        - name: COMMERCEFABRIC_USERSERVICE_DB_PASSWORD
          value: admin
        - name: COMMERCEFABRIC_AZURE_ENTRA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: users-microservice-secrets
              key: COMMERCEFABRIC_AZURE_ENTRA_CLIENT_SECRET # Create this secret in aks via kubectl create secret generic users-microservice-secrets --namespace commercefabric-namespace  --from-literal=COMMERCEFABRIC_AZURE_ENTRA_CLIENT_SECRET="your-real-secret"