apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: commercefabric-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: commercefabricregistry.azurecr.io/mysql:9.7.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: productDB
        ports:
        - containerPort: 3306