apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: commercefabric-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: commercefabric-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.3.7
          ports:
            - containerPort: 27017

          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db

      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
