apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: commercefabric-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: commercefabric-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.0

          env:
            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: admin

            - name: POSTGRES_DB
              value: commercefabricUsers

          ports:
            - containerPort: 5432

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
