apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-seed-sql
  namespace: commercefabric-namespace
data:
  db_users_seed.sql: |
    CREATE TABLE IF NOT EXISTS public.users (
        UserID UUID PRIMARY KEY,
        Gender VARCHAR(50) NOT NULL,
        Bio VARCHAR(500)
    );